### ISSUE TITLE
S3 console gives problematic URLs 

### ISSUE THREAD

**Issue by Liath** [mhart/aws4fetch#13]
S3 console gives problematic URLs, they take the form:
`<bucket_name>.s3-<region>.amazonaws.com`
Note the `-` instead of a `.` after `s3`.

This causes service/region guess to fail. Illustrated here:
![image](https://user-images.githubusercontent.com/1565435/80057269-fb2d2c00-84da-11ea-8649-14eb3ece23c8.png)
region is `s3-us-west-2` and service is the bucket name.

I think this might be a reasonable patch if you're not too opposed to adding another regex:
```diff
--- node_modules/aws4fetch/dist/aws4fetch.cjs2.js       2020-04-22 21:05:03.136867900 -0700
+++ node_modules/aws4fetch/dist/aws4fetch.cjs.js        2020-04-22 21:00:49.403364900 -0700
@@ -270,6 +270,9 @@
   } else if (region === 's3' || region === 's3-accelerate') {
     region = 'us-east-1';
     service = 's3';
+  } else if (/^s3-\w+-\w+-\d+/.test(region)) {
+    region = region.substring(3);
+    service = 's3';
   } else if (service === 'iot') {
     if (hostname.startsWith('iot.')) {
       service = 'execute-api';
```

**Comment by mhart** [comment]
Can you show me where you encountered these URLs? I can't see them in the S3 Console anywhere

**Comment by Liath** [comment]
Sure, if you go to any object's page, it'll be at the bottom of the listing. Here's an example:
![image](https://user-images.githubusercontent.com/1565435/82498745-58e67100-9aa5-11ea-8bd4-9d6b0c4f7c78.png)

**Comment by mhart** [comment]
So weird, it doesn't do that for me.

I wonder if it's region specific?

<img width="629" alt="Screen Shot 2020-05-20 at 7 05 34 PM" src="https://user-images.githubusercontent.com/367936/82506102-e8ebe100-9acc-11ea-862a-d7a3b8b0fc7e.png">

**Comment by mhart** [comment]
Turns out it's deprecated – not sure why S3 Console still uses that for some regions?

https://twitter.com/Avarmax/status/1263281775331213314

Not sure whether I should add support for it or not, considering it's discouraged 😬

**Comment by mhart** [comment]
More details here on this being a legacy format here: https://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html#s3-dash-region

**Comment by Liath** [comment]
Yeah they're kind of rare. I only ran into them because I'm in us-west-2 a lot and I'm doing request signing from a WebExtension.

**Comment by mhart** [comment]
Ah. Can you modify the hostname to the preferred format if you run into it? I kinda feel like it's better to not have an exception for this if AWS doesn't want ppl to use it anymore.

**Comment by Liath** [comment]
Yeah, that's what I'm gonna do, Thanks for taking a look :)
