### ISSUE TITLE
Not working when fetching object with DigitalOcean Spaces

### ISSUE THREAD

**Issue by jdelk** [mhart/aws4fetch#15]
Here’s the code I’m running:

```
import { AwsClient } from 'aws4fetch'

const aws = new AwsClient({

    "accessKeyId": 'ACCESS_KEY_HERE',

    "secretAccessKey": 'SECRET_ACCESS_KEY_HERE',

    "region": 'nyc3'

});

addEventListener('fetch', function (event) {

    event.respondWith(handleRequest(event.request))

});

async function handleRequest(request) {

    var url = new URL(request.url);

    url.hostname = 'bucketname.nyc3.digitaloceanspaces.com';

    var signedRequest = await aws.sign(url);

    return await fetch(signedRequest, { "cf": { "cacheEverything": true } });

}
```

DigitalOcean Spaces supports AWS Signature 4 according to their docs: https://developers.digitalocean.com/documentation/spaces/#authentication

So I’m not sure what I'm doing wrong here. I'd appreciate any help you can provide.

**Comment by mhart** [comment]
No idea – there's no specific support for Digital Ocean here so you're on your own I'm afraid.

Are there no error messages to tell you what's wrong?

The only thing that looks weird to me is that you're manually messing with the URL, so maybe see if there's something around that? Perhaps try constructing the URL from scratch and see if that helps

**Comment by jdelk** [comment]
Totally get that you can't really help with DigitalOcean, I appreciate your response.

No errors that are helpful -- if I change it to sign the query instead, it gives an error saying Access Denied. I'm 100% sure that the API keys I'm using are right too since they work with the Go S3 SDK for uploading files.

I've tried constructing the URL from scratch too but no dice there either.

Oh well, I'll keep trying stuff and see if I can get something to work. If I do, I'll comment here.

**Comment by jdelk** [comment]
So the solution was really simple:

`var signedRequest = await aws.sign(url, { "aws": { "service": "s3" } });` fixes it since it doesn't detect that it's S3 automatically (to be expected since this package was really intended for use with AWS)

**Comment by febg11** [comment]
Does this still work? Everything I do results in access denied
