### ISSUE TITLE
Cannot handle # correctly

### ISSUE THREAD

**Issue by OrwillT** [mhart/aws4fetch#25]
I deploy a worker on Cloudflare.

```
import { AwsClient } from 'aws4fetch'

const HTML = 'Hello World'

const aws = new AwsClient({
    "accessKeyId": AWS_ACCESS_KEY_ID,
    "secretAccessKey": AWS_ACCESS_KEY_SECRET,
    "region": AWS_S3_REGION
});

addEventListener('fetch', function(event) {
    event.respondWith(handleRequest(event.request))
});

async function handleRequest(request) {
    var url = new URL(request.url);    
    url.hostname = AWS_S3_BUCKET + '.' + AWS_S3_ENDPOINT;

    var signedRequest = await aws.sign(url);

    if (url.pathname === '/') {
        return new Response(HTML, { headers: { 'Content-Type': 'text/html; charset=utf-8' }});
    } else {
        return await fetch(signedRequest, { "cf": { "cacheEverything": true } });
    }
}
```

And it cannot handle non-English characters.

For example:

https://assets.anislet.dev/Example.txt

https://assets.anislet.dev/サンプル.txt

**Comment by OrwillT** [comment]
Tried with newest release, still not work.

For example:

https://late-darkness-bd7e.anislet.workers.dev/b2/hinata/中文.txt
https://late-darkness-bd7e.anislet.workers.dev/b2/hinata/%E4%B8%AD%E6%96%87.txt

Backend is backblaze.

**Comment by mhart** [comment]
I don't know anything about Backblaze – you'll have to provide more information on the errors you're seeing, and what the problem is. This library is only tested against AWS services

**Comment by OrwillT** [comment]
Here is the [doc](https://www.backblaze.com/b2/docs/s3_compatible_api.html) of Backblaze's S3 Compatible API which they claim could move application from AWS to it smoothly.

I found there is a test suite, I'm trying to make a test with Backblaze but can't find a clue yet.

The problem is with the same access key and secret key, if there is even one non-English character in the url (which will be encode to format like `%XX`), this request will fail with SignatureDoesNotMatch.

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Error>
    <Code>SignatureDoesNotMatch</Code>
    <Message>Signature validation failed</Message>
</Error>
```

**Comment by OrwillT** [comment]
@mhart So I figure it out now.

https://github.com/mhart/aws4fetch/blob/b3aed16b6f17384cf36ea33bcba3c1e9f3bdfefd/src/main.js#L212-L214

I don't know what AWS is but with Backblaze both `service` and `singleEncode` are undifend. Then those three line above will encode the uri again and make it to something really wired. That's why `SignatureDoesNotMatch` happend.

![image](https://user-images.githubusercontent.com/21377465/94410119-9375be00-01a9-11eb-9b21-2e06fd9a9488.png)

I'll send a pull request later to fix this issue.

**Comment by mhart** [comment]
You need to set `service` to be `s3`. See if that works

**Comment by OrwillT** [comment]
Yes, you're right, that fix it.

And I found another bug. it can't handle `#` correctly and need to manually change them to `%23`

https://api.anislet.dev/b2/hinata/第１回【#コンパスひなたEJ杯】開催だァ！！！-h8JbX9wtKm0.mp4
https://api.anislet.dev/b2/hinata/第１回【%23コンパスひなたEJ杯】開催だァ！！！-h8JbX9wtKm0.mp4

```
<Error>
    <Code>NoSuchKey</Code>
    <Message>Key not found</Message>
</Error>
```

**Comment by mhart** [comment]
That's not the responsibility of this library – `#` has a specific meaning in URLs and is not sent to the server – this library is still signing the path correctly (which is why backblaze is not throwing a signing error here)

**Comment by OrwillT** [comment]
I understand.

Thanks for your help, sincerely.
