### ISSUE TITLE
Trying to Insert in DynamoDB

### ISSUE THREAD

**Issue by Javeed-JargonHandlers** [mhart/aws4fetch#27]
I am need to insert into DynamoDB table using aws4fetch is there any example.

Looking for the suggestion

**Comment by mhart** [comment]
Hi Javeed – this repo is for singing requests to AWS API endpoints. There are hundreds of API endpoints, and these are documented over at AWS. You can find documentation on the DynamoDB API here: https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/Welcome.html

**Comment by Javeed-JargonHandlers** [comment]
Hi @mhart ,

Thank you for the response, I would like to know the signing endpoint may i insert the data?

**Comment by mhart** [comment]
DynamoDB endpoints are documented here: https://docs.aws.amazon.com/general/latest/gr/ddb.html

**Comment by XavM** [comment]
Fo reference, and any one ending up here trying to `aws.fetch` the DynamoDB API, you need to add 2 headers  

```
'Content-Type': 'application/x-amz-json-1.0',
'X-Amz-Target': `DynamoDB_20120810.${dynamodbAction}`
```

Ex for a `GetItem`: 
```
const regionCode = 'us-east-1',
          DYNAMODB_API = `https://dynamodb.${regionCode}.amazonaws.com`,
          query = {
            "TableName": "yourTable",
            "Key": {
              "id": {
                "S": "yourKey"
              }
            },
            "ConsistentRead": false,
            "ReturnConsumedCapacity": "INDEXES"
          }

async function getKey(body) {
  const res = await aws.fetch(DYNAMODB_API, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/x-amz-json-1.0',
            'X-Amz-Target': 'DynamoDB_20120810.GetItem'
          },
          body: JSON.stringify(request)
        })

  return res.json()
}
```

List of DynamoDB Actions : https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Operations_Amazon_DynamoDB.html
