### ISSUE TITLE
Cross account calls possible?

### ISSUE THREAD

**Issue by DavidWells** [mhart/aws4fetch#30]
Hey Michael 👋

This library is awesome. Thanks you!

---

I'm trying to make a cross-account call for the pinpoint service.

Account A `111111111111` holds the Cognito user pool and is minting the creds `awsfetch` is using

Account B `222222222222` holds the pinpoint service. Both in the same region.

When making the fetch call in a single account everything just works ™

When making the call across accounts I get this error back

```
// req to https://pinpoint.us-east-1.amazonaws.com/v1/apps/123456789/events
{"message":
 "User: arn:aws:sts::111111111111:assumed-role/blah-IdentityPoolUnauthenticatedRole-1HMXYI2Z7K8DF/CognitoIdentityCredentials 
 is not authorized to perform: mobiletargeting:PutEvents 
 on resource: arn:aws:mobiletargeting:us-east-1:111111111111:apps/123456789/events"}
```

Inspecting the error, it looks like the account ID on the resource is wrong. It's hitting account `111111111111` and should be hitting account `222222222222 ` eg `arn:aws:mobiletargeting:us-east-1:222222222222:apps/123456789/events`

Is the account ID of the request automatically inferred by AWS somehow? I can't seem to find that in the construction of the signed request.

Do you know if it is possible to make a cross-account signed request from the client? 

Thanks again for the lib. You saved me very many kbs ❤️

**Comment by mhart** [comment]
Hey man!

The account ID is inferred by the creds you're using – there's nothing else in the AWS 4 signing scheme that can be used there. Because you're not getting a signature error, this library is working as expected.

I would have thought by looking at your error that it's an issue either with the app ID you're using, or the way you're calling pinpoint – pinpoint should be looking up who the owner of app ID `123456789` is before checking whether user `111111111111` has permissions on it – the error implies that the app is owned by `111111111111`. So either the error is a bit misleading (and maybe you need to give the user permissions for PutEvents on its own account, or both accounts), or the app is actually owned by `111111111111`

**Comment by mhart** [comment]
If you're still banging your head, try seeing if you can get it working with the AWS SDK and just see what calls it's making

**Comment by mhart** [comment]
@DavidWells how'd you go here?

**Comment by DavidWells** [comment]
It looks like it's not possible to call a cross-account pinpoint endpoint b/c the account ID is inferred by the signing credentials when hitting the `https://pinpoint.${pinpointRegion}.amazonaws.com/v1/apps` endpoint.

I think the answer here is to use a lambda middle man with AWS::Lambda::Permission pointing to the other account

```yml
    UnAuthedFuncPermission:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName: !GetAtt TestfuncLambdaFunction.Arn
        Action: lambda:InvokeFunction
        Principal: arn:aws:iam::OtherAcount123:role/todo-api-dev-IdentityPoolUnauthenticatedRole-1HMXYI2Z7K8DF
```

Using the lambda endpoint cross-account does work in this call b/c you can use the full function ARN in the call

```js
const aws = new AwsClient({
  accessKeyId: anonymousUser.accessKeyId,
  secretAccessKey: anonymousUser.secretAccessKey,
  sessionToken: anonymousUser.sessionToken,
})
// https://docs.aws.amazon.com/lambda/latest/dg/API_Invoke.html
const LAMBDA_FN_API = 'https://lambda.us-east-1.amazonaws.com/2015-03-31/functions'

async function invokeMyLambda(event, headers) {
  console.log('Call pinpoint', event)
  const funcArn = 'arn:aws:lambda:us-east-1:11311221211:function:my-func-name'
  const res = await aws.fetch(`${LAMBDA_FN_API}/${funcArn}/invocations`, {
    headers: headers,
    body: JSON.stringify(event),
  })
  return res.json()
}
```

I don't like the extra lambda invocation required here but I don't see another way around this as it appears AWS pinpoint doesn't support resource policies

**Comment by mhart** [comment]
Ok cool – thanks for the update. Have you checked with AWS support whether there'd be a way to do this for pinpoint? Seems like a bit of an annoying limitation – but then I guess most ppl would just have their users all in the one account
