### ISSUE TITLE
Installing via npm includes missing type definitions

### ISSUE THREAD

**Issue by nwehner** [mhart/aws4fetch#33]
I just installed version 1.0.13 on NPM. When trying to compile JS from TS with any imports from AwsV4Signer or AwsClient, TypeScript 4.0.5 throws an series of 17 errors related to missing type definitions in `node_modules/aws4fetch/dist/main.d.ts`. 

All the missing types seem to be from the Request library from the most part, I think. I noticed in aws4fetch's tsconfig that declarations are not enabled -- and I think that's the problem. Adding { declaration: true } to tsconfig.json should make the compiler include all the required type definitions that it otherwise leaves out (because that's a sane default...?). Also I should note that adding { sourceMap: true } helps you link up TS --> JS directly in debugging which is awesome.

Would you mind including the type definitions in your next update, please? Thank you!

**Comment by mhart** [comment]
You sure you've got your typescript setup for a web environment? Objects like Request, etc are inbuilt globals

**Comment by nwehner** [comment]
Yup, didn't realize I'd need to tell TypeScript to include the DOM library in an API that never touches the DOM...again, Microsoft, sane defaults would be much appreciated lol
