### ISSUE TITLE
Lambda Function URL decoding

### ISSUE THREAD

**Issue by Manouchehri** [mhart/aws4fetch#45]
At the moment, it doesn't appear that Lambda Function URLs are decoded properly. Here's an example of one:

```text
ibvt72cx3dkyksnw7jktvkwhme0legmv.lambda-url.us-east-1.on.aws
```

https://docs.aws.amazon.com/lambda/latest/dg/lambda-urls.html

The format will always be:
```text
https://<url-id>.lambda-url.<region>.on.aws
```

As a temporary workaround, I'm manually setting `service` and `region`.
```javascript
const aws = new AwsClient({ accessKeyId: env.AWS_ACCESS_KEY_ID, secretAccessKey: env.AWS_SECRET_ACCESS_KEY, service: "lambda", region: "us-east-1" });
```

**Comment by Manouchehri** [comment]
Full example of usage for those that are curious: https://github.com/Manouchehri/cloudflare-worker-to-aws-lambda-function-url-example/blob/main/src/index.ts

**Comment by Manouchehri** [comment]
I've gone ahead and published this fork to use in the meantime: https://www.npmjs.com/package/@aimoda/aws4fetch

**Comment by mhart** [comment]
Setting `service` and `region` is a perfectly normal thing to do, supported by the API – I wouldn't call it a "workaround".

This is expected for any service created after this library was written

**Comment by Manouchehri** [comment]
> This is expected for any service created after this library was written

Right, that makes sense, which is why I made #48 for you. =)

**Comment by mhart** [comment]
> Right, that makes sense, which is why I made #48 for you. =)

I appreciate that, including the test! Will get onto it in the next couple of days. Of course part of me doesn't want this library to keep growing with every new service – but hopefully they won't continue to add ones that use different URL schemes.
