### ISSUE TITLE
Providing custom headers when using signQuery results in incorrect SignedHeaders

### ISSUE THREAD

**Issue by KianNH** [mhart/aws4fetch#46]
## Issue

When using `signQuery: true` to create presigned URLs, and also providing the `X-Amz-Expires` header to control expiry, aws4fetch is adding `x-amz-expires` into the `x-amz-signedheaders` parameter.

Since presigned URLs should only utilise query parameters and nothing else, requests will not include the `X-Amz-Expires` request header and is rejected.

This behaviour has been tested against Cloudflare R2 and Amazon S3, both of which reject the request with a `SignatureDoesNotMatch` error.

## Reproduction

This is a Cloudflare Worker.

```ts
import { AwsClient } from "aws4fetch";

export default <ExportedHandler>{
  async fetch() {
    const ACCOUNT_ID = "";
    const ACCESS_KEY_ID = "";
    const SECRET_ACCESS_KEY = "";
    const BUCKET_NAME = "";

    const R2_URL = `https://${ACCOUNT_ID}.r2.cloudflarestorage.com`;

    const client = new AwsClient({
      accessKeyId: ACCESS_KEY_ID,
      secretAccessKey: SECRET_ACCESS_KEY,
    });

    const request = new Request(`${R2_URL}/${BUCKET_NAME}/dog.png`, {
      method: "PUT",
    });

    const signed = await client.sign(request, {
      aws: { signQuery: true },
      headers: {
        "X-Amz-Expires": 3600,
      },
    });

    const response = await fetch(signed.url, {
      method: "PUT",
      body: "123",
      // Uncomment me and it'll work!
      // headers: {
      //   "X-Amz-Expires": "3600",
      // },
    });

    console.log(signed.url);
    console.log(response.status, await response.text());

    return new Response("lol");
  },
};
```

**Comment by mhart** [comment]
I'm a bit unclear why you're adding the `X-Amz-Expires` to be signed in the first place?

**Comment by mhart** [comment]
Like, what does this do?
```js
    const signed = await client.sign(request, {
      aws: { signQuery: true },
    });

    const response = await fetch(signed.url, {
      method: "PUT",
      body: "123",
      headers: {
         "X-Amz-Expires": "3600",
      },
    });
```

**Comment by mhart** [comment]
Also, isn't `X-Amz-Expires` a required query param for S3 if you're signing the request? So it should just be on the query, not the headers, right?

**Comment by KianNH** [comment]
You're correct - the original code comes from https://developers.cloudflare.com/r2/data-access/s3-api/presigned-urls/#presigned-url-alternative-with-workers which puts the `X-Amz-Expires` as a request header.

I hadn't realised that it wasn't even populating the `X-Amz-Expires` query value anyways, I was just too focused on thinking that the documented code *should* work as people didn't report that it was incorrect.

**Comment by mhart** [comment]
Right. I think this should work (assuming you want a custom X-Amz-Expires value):
```js
const request = new Request(`${R2_URL}/${BUCKET_NAME}/dog.png?X-Amz-Expires=3600`, {
  method: "PUT",
});
```

**Comment by KianNH** [comment]
It does indeed - I'll raise the issue on Cloudflare's docs. Thanks & sorry for the confusion!

**Comment by mhart** [comment]
I guess a more object-y way of doing it might be:
```js
const requestUrl = new URL('...')
requestUrl.searchParams.set('X-Amz-Expires', '3600')
```

**Comment by mhart** [comment]
Or even:
```js
requestUrl.search = new URLSearchParams({
  'X-Amz-Expires': 3600,
  // etc...
})
```

Such a pity there's no way to do this in the URL constructor...?
