### ISSUE TITLE
InvalidSignatureException on redirect fetch in CF Worker

### ISSUE THREAD

**Issue by Manouchehri** [mhart/aws4fetch#51]
Say you have the following bit of code:

```javascript
const lambdaResponse = await aws.fetch(target_url, {
	method: request.method,
	headers: cleaned_headers,
	body: request_body,
})
```

And you're getting this error message when a redirect (302, 307, etc) is returned:
```
{"message":"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details."}
```

This is _not_ an error with aws4fetch, it's because your `fetch` is making a follow-up request that is not signed properly. You can solve this by just telling fetch not to follow the redirect automatically.

e.g. the fix is:
```javascript
const lambdaResponse = await aws.fetch(target_url, {
	method: request.method,
	headers: cleaned_headers,
	body: request_body,
	redirect: "manual"
})
```

**Comment by Manouchehri** [comment]
Closing as this is not a bug with aws4fetch, only wanted to document this issue and solution for others.

**Comment by mhart** [comment]
Thanks for documenting this @Manouchehri – I must admit I've never encountered a 3xx using AWS signing before, so hadn't really thought about fetch's default behavior here.

I feel like, as you say, `aws4fetch` probably shouldn't do anything special here. If it tried to detect whether the user had the `redirect` setting unset or `follow`, but then behind the scenes set it to `manual` and intercepted, signed and made the new request – it might sound like that's the right thing to do – but `aws4fetch` has no idea if the URL being redirected to needs to be signed or not, even if it happened to be on the same host as the original request. So I think it's less magic to just leave it as is.

I'll add a note to the documentation about this when I get the chance, thanks again.
