### ISSUE TITLE
Sign URLs without protocol

### ISSUE THREAD

**Issue by revmischa** [mhart/aws4fetch#53]
I'd love to use this module to sign an IAM-authorized connection to a WebSocket API Gateway.

Unfortunately it tries to parse the URL you're asking it to sign ([here](https://github.com/mhart/aws4fetch/blob/master/src/main.js#L154)) but in the case of websockets you are apparently supposed to leave off the protocol (see https://medium.com/@o.bredenberg/iam-sign-your-api-gateway-websocket-connection-request-no-custom-auth-from-your-frontend-65451166757d).

It'd be nice if I could pass in an "invalid" URL to be signed.

Thanks!

**Comment by mhart** [comment]
I'm unlikely to add custom URL parsing myself, so it's doubtful I'd consider moving away from `new URL()`.

What happens when you pass a websocket URL to the signer? Eg call https://github.com/mhart/aws4fetch#promiserequest-awssigninput-init with `wss://...`

**Comment by mhart** [comment]
(that blog post is confusing "hosts"/"hostnames" with "URLs" btw. The signing doesn't use the protocol from the URL at all – so even if `wss://` doesn't work, you could use `http://` or `https://` and the signature would still be correct)

**Comment by revmischa** [comment]
> What happens when you pass a websocket URL to the signer? Eg call https://github.com/mhart/aws4fetch#promiserequest-awssigninput-init with `wss://...`

I'm getting unauthorized when I try to connect so I'm trying to narrow down exactly what's wrong with my signature but it's not the easiest thing to debug.
