### ISSUE TITLE
TypeScript interfaces (definition files)

### ISSUE THREAD

**Issue by MickL** [mhart/aws4fetch#6]
Could you please add interfaces for TypeScript? Currently everything is undefined/unknown.

**Comment by mhart** [comment]
I don't use TypeScript for this project – but feel free to create a PR and I'll check it out 👍

**Comment by MickL** [comment]
Problem is that i am not as much into the functions and what they need and return. I think only the developer can do this properly.

**Comment by marcogrcr** [comment]
@MickL I don't believe you did anything wrong. I have submitted a new pull request to address this (and other issues), as well as add types testing (#16).
