### ISSUE TITLE
Feat: Make execute-api default service for API Gateway with custom URL

### ISSUE THREAD

**Issue by ShivamJoker** [mhart/aws4fetch#63]
I had a custom domain with API Gateway.
Struggled for an hour to get it to work, as a workaround we can pass `"execute-api"` in the `service` param to make it work.

Here is the config:
```js
const signer = new AwsV4Signer({
  url,
  accessKeyId: accessKeyId as string,
  secretAccessKey: secretKey as string,
  region: "ap-south-1",
  service: "execute-api",
  method: "GET",
});
```
Make sure to include region in the param.

**Comment by mhart** [comment]
That’s not a “workaround”, that’s how you correctly specify the service.

**Comment by ShivamJoker** [comment]
@mhart I see, is there any doc list of AWS where we can see this list?
I tried and couldn't find.
Thanks!
