### ISSUE TITLE
Not working in SvelteKit?

### ISSUE THREAD

**Issue by vytskalt** [mhart/aws4fetch#70]
Not sure if this is a bug, but I'm getting this output from AWS when trying to use aws4fetch (server-side) in my SvelteKit app:
```
<AccessDeniedException>
  <Message>Unable to determine service/operation name to be authorized</Message>
</AccessDeniedException>
```
Weirdly enough the exact same code works correctly standalone (node ./index.js). This is the relevant snippet:
```js
import { AwsClient } from 'aws4fetch';

const aws = new AwsClient({
    accessKeyId: 'REDACTED',
    secretAccessKey: 'REDACTED',
    region: 'eu-west-1'
})

const response = await aws.fetch(`https://lambda.${aws.region}.amazonaws.com/2015-03-31/functions/reddit-scraper/invocations`, {
    method: 'POST',
    body: JSON.stringify({
        subreddit: '',
        key: ''
    }),
    headers: {
        'Content-Type': 'application/json'
    }
});

const text = await response.text();
console.log('Lambda function response:', text);
```
Any idea why this could be the case?

**Comment by mhart** [comment]
No idea, no – that doesn't look like a signature exception though, so I think aws4fetch is signing correctly.

Best way to track it down would be to look at the compiled JavaScript that SvelteKit produces and see what's going on there.

**Comment by vytskalt** [comment]
Ok, so I figured it out. It's some weird issue when running SvelteKit with the Bun runtime. When passing a Request object to fetch(), the headers and the body are being ignored for some reason.

I had to do this to make it work:
```js
    const req = await aws.sign(
        `https://lambda.${aws.region}.amazonaws.com/2015-03-31/functions/reddit-scraper/invocations`,
        {
            method: 'POST',
            body,
            headers: {
                'Content-Type': 'application/json'
            }
        }
    );

    const response = await fetch(req.url, {
        method: req.method,
        body: req.body,
        headers: req.headers
    });
```

Hope this helps somebody.
