### ISSUE TITLE
Signature expired on skewed system clock 

### ISSUE THREAD

**Issue by saksh-05** [mhart/aws4fetch#73]
I have a skewed system clock that I can't sync, and when I make a request, I receive an error:
`{
    "message": "Signature expired: 20241008T195522Z is now earlier than 20241008T195940Z (20241008T200440Z - 5 min.)"
}` 

And I am also unable to pass a custom x-amz-date header value, as it gives me:
`"message":"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.`

This is how I am passing the header before signing the request however, aws4fetch uses the system time instead of the provided value.
```javascript
const clockValue = new Date(currentSystemTime.getTime() - offset)
        .toISOString()
        .replace(/[:-]|\.\d{3}/g, "");
const request = new Request(url, {
        method: "GET",
        headers: {
          "x-amz-date": clockValue,
        },
});
```
And if I modify the header after signing, as shown below, I receive the following message: `"message":"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.`
 ```javascript
const signedRequest = await aws.sign(request);
const headers = {};
signedRequest.headers.forEach((value, key) => {
        headers[key] = value;
   });
headers["x-amz-date"] = clockValue;
```
      
Is there any solution I can use?

**Comment by mhart** [comment]
You can use [the `datetime` parameter of fetch/sign](https://github.com/mhart/aws4fetch/tree/master?tab=readme-ov-file#promiseresponse-awsfetchinput-init)

**Comment by mhart** [comment]
Gonna close this out – pretty sure `datetime` will cover your needs
